#!/bin/bash

if command -v brew &> /dev/null
then 
	if ! command -v postgresql &> /dev/null
	then
		echo "installing postgresql cli..."
		brew install postgresql
	else
		echo "psql cli already installed"
	fi
	if ! command -v redis &> /dev/null
	then
		echo "installing redis cli..."
		brew install redis
	else
		echo "redis cli already installed"
	fi
	
fi
