#!/bin/bash

if command -v brew &> /dev/null
then 
	if ! command -v psql &> /dev/null
	then
		echo "installing postgresql cli..."
		brew install postgresql
	else
		echo "psql cli already installed"
	fi
	if ! command -v redis-cli &> /dev/null
	then
		echo "installing redis cli..."
		brew install redis
	else
		echo "redis cli already installed"
	fi
else
	echo "brew is not installed. \nskipping checks for: \n[postgresql, redis-cli]"
	echo "use: zsh install-brew"
	exit
fi

cp $DOTFILES/wallpapers/astronaut_wallpaper_macos.jpg ~/Documents/Wallpapers/astronaut_wallpaper.jpg
osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/Users/chani/Documents/Wallpapers/astronaut_wallpaper.jpg"'